### ISSUE TITLE
geo app: layer panel is taller than the map and overflows it

### ISSUE THREAD

**Issue by gordom6** [tetherless-world/twxplore#62]
![Screen Shot 2020-05-11 at 8 49 31 AM](https://user-images.githubusercontent.com/52333044/81563543-60e73800-9364-11ea-8d79-c11329db5c7c.png)

**Comment by TheCovenant** [comment]
The map is set to read-only for this application, and the layer panel should not show up as long as data loads in as the application starts. 
Does the layer panel always show up like this for you?

**Comment by gordom6** [comment]
I believe this was an artifact of having an empty store. Not relevant now.
